# Generated by Django 4.2.7 on 2025-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decimals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('d_name', models.CharField(blank=True, max_length=256, null=True)),
                ('d_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'decimals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('operation', models.CharField(max_length=128)),
                ('worker', models.CharField(max_length=256)),
                ('dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'operations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iv', models.CharField(blank=True, max_length=256, null=True)),
                ('aes_key', models.CharField(blank=True, max_length=256, null=True)),
                ('date_last_conn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=256, unique=True)),
                ('access', models.IntegerField()),
            ],
            options={
                'db_table': 'user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WgBonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_login', models.IntegerField()),
                ('g_name', models.IntegerField()),
            ],
            options={
                'db_table': 'wg_bonds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_login', models.CharField(max_length=256, unique=True)),
                ('w_passhash', models.CharField(max_length=256)),
                ('w_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'workers',
                'managed': False,
            },
        ),
    ]
